# Generated by Django 6.1 on 2026-08-18 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortUrl', models.CharField(max_length=10, unique=True)),
                ('mainUrl', models.CharField(max_length=2048)),
                ('accessed', models.IntegerField(default=0)),
            ],
        ),
    ]
